workflows:
  ios-build:
    name: OpenClaw iOS Build
    max_build_duration: 60
    environment:
      xcode: "26.1"
      node: 22
      swift: "6.0"
    instance_type: mac_mini_m2_pro
    scripts:
      - name: install dependencies
        script: |
          npm install -g pnpm
          pnpm install
      - name: generate Xcode project
        script: |
          cd apps/ios
          pnpm exec xcodegen generate
      - name: Build iOS
        script: |
          cd apps/ios
          xcodebuild build -project OpenClaw.xcodeproj -scheme OpenClaw -destination "generic/platform=iOS Simulator" CODE_SIGNING_ALLOWED=NO
    artifacts:
      - apps/ios/build/**
