workflows:
  ios-build:
    name: OpenClaw ios Build
    max_build_duration: 60
    environment:
      xcode: latest
      node: 22
    scripts:
      - name: install dependencies
        script: |
          npm install -g pnpm
          pnpm install

        - name: generate Xcode project
         script: |
          \tcd apps/ios
          \tpnpm ec xcodegen generate

        - name: Build ios
         script: |
          \tcd apps/ios
          \tcodebuild build -project OpenClaw^.xcodeproj -scheme OpenClaw -destination "generic/platform=ioS Simulator" CODE_SIGNING_ALLOWID=NO
  artifacts:
    - apps/ios/build/**