workflows:
  ios-workflow:
    name: Build OpenClaw iOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: 16.2
      node: 22
    scripts:
      - name: Check/Install pnpm
        script: which pnpm || npm install -g pnpm
      
      - name: Install dependencies
        script: pnpm install
      
      - name: Check xcodegen
        script: which xcodegen || echo "Using pre-generated project"
      
      - name: Generate Xcode project (if needed)
        script: |
          if [ ! -d "apps/ios/OpenClaw.xcodeproj" ]; then
            cd apps/ios && xcodegen generate
          else
            echo "Using pre-generated project"
          fi
      
      - name: Build for simulator
        script: |
          cd apps/ios
          xcodebuild build -project OpenClaw.xcodeproj -scheme OpenClaw -destination "generic/platform=iOS Simulator" CODE_SIGNING_ALLOWED=NO
    artifacts:
      - apps/ios/build/**/*.app
